import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

import { Form } from "@/types/index";
import NewFormDialog from "@/components/NewFormDialog";
import Button from "@/components/Button";
import FormList from "@/components/FormList";

const Home: NextPage = () => {
  const [newFormOpen, setNewFormOpen] = React.useState(false);
  const [forms, setForms] = React.useState<Form[] | null>(null);

  React.useEffect(() => {
    const fetchForms = async () => {
      const res = await fetch(`/api/v1/forms`, {
        method: "get",
      });

      const json = await res.json();
      setForms(json);
    };

    fetchForms();
  }, []);

  const createNewForm = async (title: string, description: string) => {
    const body = {
      title,
      description,
    };

    const newForm: Form[] = await fetch(`/api/v1/forms`, {
      method: "post",
      body: JSON.stringify(body),
    })
      .then((res) => res.json())
      .catch((e) => console.log(e));

    console.log(newForm);

    setForms((prevForms) =>
      !!prevForms ? [...prevForms, ...newForm] : newForm
    );
  };

  return (
    <div>
      <Head>
        <title>Ashby Questionnaire </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen dark:bg-gray-950">
        <div className="w-full px-8 py-6 pt-10 mx-auto border border-b-0 border-gray-700 mt-14 dark:bg-gray-900 rounded-t-3xl max-w-7xl">
          <header className="flex items-center justify-between w-full mb-10">
            <h1 className="text-3xl">Your forms</h1>
            <Button onClick={() => setNewFormOpen(true)}>
              Create new form
            </Button>
          </header>
          {forms !== null ? <FormList forms={forms} /> : null}
        </div>
        <NewFormDialog
          open={newFormOpen}
          setOpen={setNewFormOpen}
          createNewForm={createNewForm}
        />
      </main>
    </div>
  );
};

export default Home;
